import * as Phaser from 'phaser'
import { Audio } from '../game/audio.js'

// ─────────────────────────────────────────────────────────────────────────────
//  DraftScene.js — Upgrade card selection between rooms
//
//  After clearing a room, the player chooses 1 of 3 upgrade cards.
//  The cards are generated by getDraftPool() which weights them toward
//  the player's dominant build archetype and checks for active synergies.
//
//  CURSE CARDS:
//  If a curse appears in the draft, tapping it shows a confirmation dialog.
//  The player can accept (gets +50% score multiplier) or skip for free.
//
//  FLOW:
//    GameScene (room clear) → DraftScene → TransitionScene (next room)
//
//  DATA RECEIVED:
//    data.nextRoomNum — which room to go to after picking an upgrade
// ─────────────────────────────────────────────────────────────────────────────

import { getDraftPool, getSynergyNote } from '../game/upgrades.js'

export class DraftScene extends Phaser.Scene {
  constructor() {
    super({ key: 'DraftScene' })
  }

  init(data) {
    this.nextRoomNum = data.nextRoomNum || 2  // Which room to enter after upgrade
    this.worldId     = data.worldId     || 'void'  // Current world id — passed forward
  }

  create() {
    const W = this.scale.width
    const H = this.scale.height
    this.W  = W
    this.H  = H

    // Read current run state from the registry
    const owned = this.registry.get('activeUpgrades') || {}  // Already-owned upgrades
    const relic = this.registry.get('selectedRelic')          // Current relic (for future synergy support)
    const room  = this.registry.get('roomNum') || 1           // Current room number (for Legendary gating)

    // Generate 3 cards using the smart draft pool logic
    const picks = getDraftPool(owned, room, relic?.id)

    // ── Background ──
    this.add.rectangle(0, 0, W, H, 0xf5f0e4).setOrigin(0, 0)
    this.drawPaperTexture()

    // ── Header ──
    this.add.text(W / 2, H * 0.05, 'ROOM CLEAR', {
      fontFamily:    'Georgia, serif',
      fontSize:      Math.round(W * 0.028) + 'px',
      color:         '#8a7a6a',
      letterSpacing: 3
    }).setOrigin(0.5)

    this.add.text(W / 2, H * 0.12, 'choose an upgrade', {
      fontFamily: 'Georgia, serif',
      fontSize:   Math.round(W * 0.065) + 'px',
      color:      '#2a1f0e'
    }).setOrigin(0.5)

    this.add.text(W / 2, H * 0.19, 'tap a card to continue', {
      fontFamily: 'Georgia, serif',
      fontSize:   Math.round(W * 0.034) + 'px',
      color:      '#8a7a6a',
      fontStyle:  'italic'
    }).setOrigin(0.5)

    // Create each card (index 0, 1, 2 — stacked vertically)
    picks.forEach((upgrade, i) => this.createCard(upgrade, owned, W, H, i))

    this.cameras.main.fadeIn(250, 245, 240, 228)
  }

  // ─────────────────────────────────────────────────────────────────────────
  //  CREATE CARD
  //  Builds one upgrade card at the given index position.
  //  Cards are stacked vertically: index 0 is highest, 2 is lowest.
  //
  //  Each card has:
  //    - Background rectangle (changes color on hover)
  //    - Tier badge (colored pill: Common/Rare/Legendary/Curse)
  //    - Upgrade name
  //    - Vertical divider separating name from description
  //    - Description text
  //    - Synergy note (in blue, only if a synergy with owned upgrades exists)
  //    - Invisible hit zone covering the whole card (for tap detection)
  // ─────────────────────────────────────────────────────────────────────────
  createCard(upgrade, owned, W, H, index) {
    const isCurse = upgrade.tier === 'Curse'
    const isRare  = upgrade.tier === 'Rare'
    const isLeg   = upgrade.tier === 'Legendary'

    // Card dimensions and position
    const cardX = W * 0.05
    const cardW = W * 0.9
    const cardH = H * 0.19
    // Stacked vertically with a small gap between cards
    const cardY = H * 0.26 + index * (cardH + H * 0.025)

    // Check if this upgrade synergises with anything the player already owns
    const synergyNote = getSynergyNote(upgrade, owned)

    // Card background — different colors for different tiers/states
    const bg = this.add.graphics()
    this.drawCard(bg, cardX, cardY, cardW, cardH, 10, false, isCurse, isRare, isLeg)

    // ── Tier badge ──
    // Color-coded by tier: green=Common, blue=Rare, amber=Legendary, red=Curse
    const badgeColors = {
      Common:    { bg: '#EAF3DE', text: '#27500A' },  // Green
      Rare:      { bg: '#E6F1FB', text: '#0C447C' },  // Blue
      Legendary: { bg: '#FAEEDA', text: '#633806' },  // Amber
      Curse:     { bg: '#FCEBEB', text: '#791F1F' },  // Red
    }
    const badge = badgeColors[upgrade.tier] || badgeColors.Common
    this.add.text(cardX + W * 0.04, cardY + cardH * 0.18, upgrade.tier, {
      fontFamily:      'Georgia, serif',
      fontSize:        Math.round(W * 0.028) + 'px',
      color:           badge.text,
      backgroundColor: badge.bg,
      padding:         { x: 6, y: 2 }
    }).setOrigin(0, 0.5)

    // "skippable" label on curse cards — signals to the player they don't have to take it
    if (isCurse) {
      this.add.text(cardX + cardW - W * 0.04, cardY + cardH * 0.18, 'skippable', {
        fontFamily: 'Georgia, serif',
        fontSize:   Math.round(W * 0.026) + 'px',
        color:      '#a89a8a',
        fontStyle:  'italic'
      }).setOrigin(1, 0.5)
    }

    // ── Upgrade name ──
    // Curse names are red to reinforce the dangerous nature
    this.add.text(cardX + W * 0.04, cardY + cardH * 0.42, upgrade.name, {
      fontFamily: 'Georgia, serif',
      fontSize:   Math.round(W * 0.048) + 'px',
      color:      isCurse ? '#791F1F' : '#2a1f0e'
    }).setOrigin(0, 0.5)

    // ── Vertical divider ──
    // Separates the left column (name/tier) from the right column (description)
    this.add.graphics()
      .lineStyle(0.5, isCurse ? 0xf09595 : 0xc4a882, 0.5)
      .lineBetween(
        cardX + cardW * 0.38, cardY + cardH * 0.1,
        cardX + cardW * 0.38, cardY + cardH * 0.9
      )

    // ── Description ──
    // Positioned higher when there's a synergy note (to make room for it below)
    this.add.text(
      cardX + cardW * 0.42,
      cardY + cardH * (synergyNote ? 0.36 : 0.5),
      upgrade.desc, {
      fontFamily:  'Georgia, serif',
      fontSize:    Math.round(W * 0.031) + 'px',
      color:       '#6a5a4a',
      wordWrap:    { width: cardW * 0.52 },
      lineSpacing: 3
    }).setOrigin(0, 0.5)

    // ── Synergy note ──
    // Only shown if the player already owns a card that synergises with this one
    // Displayed in blue with a ✦ marker to draw attention
    if (synergyNote) {
      this.add.text(cardX + cardW * 0.42, cardY + cardH * 0.78, '✦ ' + synergyNote, {
        fontFamily: 'Georgia, serif',
        fontSize:   Math.round(W * 0.026) + 'px',
        color:      '#378add',
        fontStyle:  'italic',
        wordWrap:   { width: cardW * 0.52 }
      }).setOrigin(0, 0.5)
    }

    // ── Invisible hit zone ──
    // A transparent rectangle the same size as the card, used for tap detection.
    // We use a Zone instead of making the graphics interactive because zones
    // are cheaper and don't interfere with rendering.
    const zone = this.add.zone(cardX, cardY, cardW, cardH).setOrigin(0, 0).setInteractive()

    zone.on('pointerdown', () => {
      if (isCurse) {
        // Curse: show a confirmation dialog before applying
        this.showCurseConfirm(upgrade)
        return
      }
      // Normal upgrade: apply immediately and proceed
      Audio.upgradeSelect()  // Confirmatory chime
      const currentOwned = this.registry.get('activeUpgrades') || {}
      currentOwned[upgrade.id] = true  // Add this upgrade to owned map
      this.registry.set('activeUpgrades', currentOwned)
      this.proceed()
    })

    // Hover: redraw card with hover styling
    zone.on('pointerover', () => {
      bg.clear()
      this.drawCard(bg, cardX, cardY, cardW, cardH, 10, true, isCurse, isRare, isLeg)
    })
    zone.on('pointerout', () => {
      bg.clear()
      this.drawCard(bg, cardX, cardY, cardW, cardH, 10, false, isCurse, isRare, isLeg)
    })
  }

  // ─────────────────────────────────────────────────────────────────────────
  //  SHOW CURSE CONFIRM
  //  Overlays a dialog asking the player whether to accept or skip the curse.
  //  Accepting applies the curse AND grants +50% score multiplier.
  //  Skipping has no effect — the player just moves on without an upgrade.
  // ─────────────────────────────────────────────────────────────────────────
  showCurseConfirm(upgrade) {
    const W = this.W
    const H = this.H

    // Dark semi-transparent overlay behind the dialog box
    this.add.rectangle(0, 0, W, H, 0x000000, 0.5).setOrigin(0, 0)

    // Dialog box dimensions
    const bx = W * 0.08, by = H * 0.28
    const bw = W * 0.84, bh = H * 0.44

    // Dialog background and border
    const box = this.add.graphics()
    box.fillStyle(0xfaf6ee, 1)
    box.fillRoundedRect(bx, by, bw, bh, 12)
    box.lineStyle(2, 0xf09595, 1)   // Red border — curse is dangerous
    box.strokeRoundedRect(bx, by, bw, bh, 12)

    // Dialog content
    this.add.text(W / 2, by + bh * 0.15, 'Accept this curse?', {
      fontFamily: 'Georgia, serif',
      fontSize:   Math.round(W * 0.048) + 'px',
      color:      '#791F1F'
    }).setOrigin(0.5)

    this.add.text(W / 2, by + bh * 0.36, upgrade.desc, {
      fontFamily: 'Georgia, serif',
      fontSize:   Math.round(W * 0.032) + 'px',
      color:      '#6a5a4a',
      align:      'center',
      wordWrap:   { width: bw * 0.8 }
    }).setOrigin(0.5)

    // The reward — makes accepting the curse worthwhile
    this.add.text(W / 2, by + bh * 0.58, 'Reward: +50% score multiplier this run', {
      fontFamily: 'Georgia, serif',
      fontSize:   Math.round(W * 0.03) + 'px',
      color:      '#8a4020',
      fontStyle:  'italic'
    }).setOrigin(0.5)

    // Accept button — applies curse + multiplier
    const acceptBtn = this.add.text(W / 2 - W * 0.16, by + bh * 0.8, 'accept curse', {
      fontFamily:      'Georgia, serif',
      fontSize:        Math.round(W * 0.036) + 'px',
      color:           '#f5f0e4',
      backgroundColor: '#791F1F',
      padding:         { x: 14, y: 8 }
    }).setOrigin(0.5).setInteractive()

    // Skip button — no effect, just continues
    const skipBtn = this.add.text(W / 2 + W * 0.16, by + bh * 0.8, 'skip', {
      fontFamily:      'Georgia, serif',
      fontSize:        Math.round(W * 0.036) + 'px',
      color:           '#2a1f0e',
      backgroundColor: '#e8e0d0',
      padding:         { x: 14, y: 8 }
    }).setOrigin(0.5).setInteractive()

    acceptBtn.on('pointerdown', () => {
      // Apply the curse upgrade
      const currentOwned = this.registry.get('activeUpgrades') || {}
      currentOwned[upgrade.id] = true
      this.registry.set('activeUpgrades', currentOwned)

      // Stack the score multiplier (1.5× — can stack if multiple curses are accepted)
      this.registry.set('scoreMultiplier',
        (this.registry.get('scoreMultiplier') || 1) * 1.5
      )
      this.proceed()
    })

    skipBtn.on('pointerdown', () => {
      // Skip: no upgrade applied, just move to the next room
      this.proceed()
    })
  }

  // ─────────────────────────────────────────────────────────────────────────
  //  PROCEED
  //  Navigates to the transition screen for the next room.
  //  Called after any card selection (normal, curse accepted, or curse skipped).
  // ─────────────────────────────────────────────────────────────────────────
  proceed() {
    this.cameras.main.fadeOut(200, 245, 240, 228)
    this.cameras.main.once('camerafadeoutcomplete', () => {
      // nextRoomNum 4 = boss room; route to TransitionScene which will then
      // go to BossIntroScene because roomNum 4 makes isBoss true
      // Pass worldId forward so TransitionScene and GameScene know which world we're in
      this.scene.start('TransitionScene', {
        roomNum: this.nextRoomNum === 4 ? 4 : this.nextRoomNum,
        worldId: this.worldId
      })
    })
  }

  // ─────────────────────────────────────────────────────────────────────────
  //  DRAW CARD
  //  Draws the card background and border with appropriate colors for tier/state.
  //  Called on initial draw and on hover/unhover to change appearance.
  //
  //  PARAMETERS:
  //    g       — Graphics object to draw on
  //    x, y    — Top-left corner
  //    w, h    — Width and height
  //    r       — Corner radius
  //    hover   — Is the mouse/finger currently over this card?
  //    isCurse, isRare, isLeg — Tier flags for color selection
  // ─────────────────────────────────────────────────────────────────────────
  drawCard(g, x, y, w, h, r, hover, isCurse, isRare, isLeg) {
    // Fill: slightly different background when hovering
    g.fillStyle(hover
      ? (isCurse ? 0xfce8e8 : 0xf0ead8)   // Hover: warm pink for curse, warm beige for others
      : (isCurse ? 0xfdf3f3 : 0xfaf6ee),  // Normal: faint pink for curse, cream for others
      1
    )
    g.fillRoundedRect(x, y, w, h, r)

    // Border color and width by tier:
    //   Curse: red    (danger signal)
    //   Legendary: amber (premium)
    //   Rare: blue    (uncommon)
    //   Common: tan   (standard)
    // Hover increases border width for a "selected" feel
    g.lineStyle(
      isLeg || isCurse ? 2 : (hover ? 2 : 1.5),
      isCurse ? (hover ? 0xe24b4a : 0xf09595) :
      isLeg   ? (hover ? 0xba7517 : 0xef9f27) :
      isRare  ? (hover ? 0x185fa5 : 0x378add) :
                (hover ? 0x8a6a3a : 0xc4a882),
      1  // Full opacity
    )
    g.strokeRoundedRect(x, y, w, h, r)
  }

  // Draws faint horizontal lines to simulate paper texture
  drawPaperTexture() {
    const g = this.add.graphics()
    g.lineStyle(1, 0xa08060, 0.04)
    for (let y = 0; y < this.scale.height; y += 4) {
      g.lineBetween(0, y, this.scale.width, y)
    }
  }
}